print("Desea conocer el menor de 3 numeros:")
num1=int(input("Ingrese el primer numero: "))
num2=int(input("Ingrese el segundo numero: "))
num3=int(input("Ingrese el tercer numero: "))
menor=min(num1,num2,num3)
print(f"El menor numero es: {menor}")